### ISSUE TITLE
Windows 32 and 64 bit executables are named incorrectly

### ISSUE THREAD

**Issue by burgersmoke** [magsilva/dtm#3]
Looks like this is simple to address user-side, but it looks like the 32bit is actually a 64 bit binary and vice versa.  I checked this with SysInternals sigcheck.exe and also by looking in the headers.

Here's the output from sigcheck:

sigcheck.exe c:\dtm\bin\dtm-win32.exe

Sigcheck v2.60 - File version and signature viewer
Copyright (C) 2004-2017 Mark Russinovich
Sysinternals - www.sysinternals.com

c:\dtm\bin\dtm-win32.exe:
        Verified:       Unsigned
        Link date:      5:01 PM 3/23/2014
        Publisher:      n/a
        Company:        n/a
        Description:    n/a
        Product:        n/a
        Prod version:   n/a
        File version:   n/a
        MachineType:    64-bit

sigcheck.exe c:\dtm\bin\dtm-win64.exe

Sigcheck v2.60 - File version and signature viewer
Copyright (C) 2004-2017 Mark Russinovich
Sysinternals - www.sysinternals.com

c:\dtm\bin\dtm-win64.exe:
        Verified:       Unsigned
        Link date:      5:01 PM 3/23/2014
        Publisher:      n/a
        Company:        n/a
        Description:    n/a
        Product:        n/a
        Prod version:   n/a
        File version:   n/a
        MachineType:    32-bit

**Comment by burgersmoke** [comment]
Also, it may be possible that this could be the cause for a few issues like this one that some have discussed in forums:

https://groups.google.com/forum/#!topic/gensim/wRJXLYnIlTg

**Comment by magsilva** [comment]
Thank you for letting me know of this issue. I have just fixed it.

**Comment by burgersmoke** [comment]
Fantastic news.  Thank you for doing this.
